// Shared styles object — ported directly from the old index.html's inline
// `const styles = {...}`. Every component imports this instead of relying
// on a global variable, since nothing is global in a real component-based
// app. The CSS variables it references (var(--bgsu-orange), etc.) are
// defined in index.css.

export const styles = {
  page: {
    maxWidth: "var(--page-max-width)",
    margin: "0 auto",
    padding: "20px 14px 64px",
  },
  header: {
    textAlign: "center",
    marginBottom: 20,
    background: "var(--bgsu-brown)",
    color: "#fff",
    padding: "22px 16px",
    borderRadius: 8,
    borderBottom: "4px solid var(--bgsu-orange)",
  },
  card: {
    background: "#fff",
    border: "1px solid #ddd",
    borderRadius: 8,
    padding: "var(--card-padding)",
    marginBottom: 18,
  },
  savedCard: {
    background: "rgba(245, 193, 99, 0.22)",
    borderColor: "var(--bgsu-tan)",
  },
  label: {
    display: "block",
    fontWeight: "bold",
    marginBottom: 6,
  },
  input: {
    width: "100%",
    padding: "12px 10px",
    boxSizing: "border-box",
    marginBottom: 12,
    border: "1px solid #ccc",
    borderRadius: 6,
    fontSize: "calc(16px * var(--font-scale, 1))",
    minHeight: 44,
  },
  select: {
    width: "100%",
    maxWidth: 320,
    padding: "12px 10px",
    boxSizing: "border-box",
    marginBottom: 12,
    border: "1px solid #ccc",
    borderRadius: 6,
    fontSize: "calc(16px * var(--font-scale, 1))",
    minHeight: 44,
  },
  button: {
    padding: "12px 22px",
    fontSize: "calc(16px * var(--font-scale, 1))",
    borderRadius: 6,
    border: "1px solid var(--bgsu-orange)",
    background: "var(--bgsu-orange)",
    color: "#fff",
    cursor: "pointer",
    minHeight: 44,
  },
  buttonSecondary: {
    padding: "11px 20px",
    fontSize: "calc(15px * var(--font-scale, 1))",
    borderRadius: 6,
    border: "1px solid #999",
    background: "#eee",
    color: "#333",
    cursor: "pointer",
    minHeight: 44,
  },
  buttonDisabled: {
    opacity: 0.5,
    cursor: "not-allowed",
  },
  error: {
    color: "#b00020",
    fontSize: "calc(13px * var(--font-scale, 1))",
    marginBottom: 8,
  },
  help: {
    color: "#666",
    fontSize: "calc(12px * var(--font-scale, 1))",
    marginTop: 2,
    marginBottom: 8,
  },
  radioRow: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    fontSize: "calc(16px * var(--font-scale, 1))",
    fontWeight: "bold",
    cursor: "pointer",
    padding: "10px 0",
  },
  radio: {
    width: 22,
    height: 22,
    flexShrink: 0,
    accentColor: "var(--bgsu-orange)",
  },
  successBanner: {
    background: "#e6f4ea",
    border: "1px solid #b7dfc0",
    color: "#1a7a1a",
    borderRadius: 8,
    padding: 14,
    marginBottom: 18,
    fontWeight: "bold",
  },
  noticeBanner: {
    background: "rgba(245, 193, 99, 0.25)",
    border: "1px solid var(--bgsu-tan)",
    color: "#6b4a1a",
    borderRadius: 8,
    padding: "10px 14px",
    marginBottom: 18,
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 10,
    fontSize: "calc(14px * var(--font-scale, 1))",
  },
  dismissBtn: {
    border: "none",
    background: "none",
    fontSize: "calc(20px * var(--font-scale, 1))",
    cursor: "pointer",
    color: "#6b4a1a",
    lineHeight: 1,
    padding: "4px 6px",
  },
  fontScaleRow: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    gap: 8,
    marginBottom: 18,
  },
  fontScaleLabel: {
    color: "#666",
    fontSize: 12,
  },
  fontScaleButton: {
    padding: "5px 12px",
    fontSize: 12,
    borderRadius: 5,
    border: "1px solid #ccc",
    background: "#fff",
    color: "#444",
    cursor: "pointer",
    minHeight: 28,
  },
  fontScaleButtonActive: {
    border: "1px solid var(--bgsu-orange)",
    background: "var(--bgsu-orange)",
    color: "#fff",
  },
};